### ISSUE TITLE
How to install Ironbug  in Grasshooper?

### ISSUE THREAD

**Issue by ymg2007** [MingboPeng/Ironbug#14]
How to install Ironbug  in Grasshooper?

**Comment by Vanmman16TR** [comment]
Hi,

I presume you should just drop the Ironbug master folder into the Grasshopper Components folder? I have tried this but get a lot of errors when opening Grasshopper and missing toolbar icons (see attached). Are you able to assist?

Regards,

Ian

[GH_Load_Ex.txt](https://github.com/MingboPeng/Ironbug/files/2270007/GH_Load_Ex.txt)
![capture](https://user-images.githubusercontent.com/42206636/43833482-cca0b9a6-9b02-11e8-91a3-82b3048a31db.JPG)

**Comment by FlahaAG** [comment]
Installation Instructions:

1-Download the Ironbug.zip 17 (1.4 MB) and unblock the file.
![pic](https://discourse.ladybug.tools/uploads/default/original/2X/2/24e0797df218b005ae7a9e95a7be908724cb2d5e.gif)

2. Unzip to C:\Ironbug, and open 00_installer.gh in Grasshopper.
![pic](https://discourse.ladybug.tools/uploads/default/optimized/2X/5/5fe511542effa4a87dd90c7a2a435bfc6474eba9_1_690x182.png)

3. Find the OpenStudio folder path on your computer, and set toggle to true to install.
![pic](https://discourse.ladybug.tools/uploads/default/original/2X/3/3798b6a20529d3ee811124e72060f6120ef6fb5a.gif)

4. Restart the Grasshopper, and enjoy!

-Mingbo Peng - [https://discourse.ladybug.tools/t/ironbug-beta-release/3393](url)

**Comment by MingboPeng** [comment]
Thanks @FlahaAG.
@Vanmman16TR  How did you install the plugin?

**Comment by Vanmman16TR** [comment]
I was running into issues using an older version of your plugin - using your guidance above i have now successfully installed this version. Many thanks @MingboPeng!
