### ISSUE TITLE
Migrate Ironbug's LB_HB components to HB_Legacy & LB_Legacy tabs

### ISSUE THREAD

**Issue by Omidmr** [MingboPeng/Ironbug#34]
Hello @MingboPeng ,
Thank you for this great plugin and HB_LB's components.

As you probably aware, in the latest release of LB and HB legacy, they have new names in Grasshopper's tab and named:
LB_legacy and HB_legacy.
But some Ironbug's components for LB HB  like `Ladybug_ImageViewer`, `Ladybug_SortByLayers`, `Honeybee_IntersectMassII` and `Honeybee_ReadAnnualResultsIII `  are still in the Ladybug and Honeybee old names tabs. 

If it's possible for you, please update these components and move to Legacy tabs.
Thanks.

-Omid

**Comment by MingboPeng** [comment]
Hi @Omidmr thanks, I will work on this soon.

**Comment by MingboPeng** [comment]
Hi @Omidmr I'am closing this issue as I have addressed in a new ironbug [release ](https://github.com/MingboPeng/Ironbug/releases). Please update both ladybug and ironbug together.
