### ISSUE TITLE
2 versions of Open Studio

### ISSUE THREAD

**Issue by amrauf** [MingboPeng/Ironbug#39]
Hi, many thanks for the awesome plug-in. I had two versions of Open Studio installed, so  I am getting the following error while trying to use some nodes:
1. Solution exception:The type initializer for 'OpenStudio.OpenStudioModelCorePINVOKE' threw an exception.

How can I specify only one OPen Studio version to be used by Ironbug.

Many thanks

**Comment by MingboPeng** [comment]
Hi @amrauf, by default, Ironbug always loads the newest version. If you want it to load a certain version, you can copy libraries from OpenStuido\CSharp\openstudio folder to C:\Ironbug, which Ironbug will check first.

**Comment by amrauf** [comment]
Thanks MingboPeng! I think my latest Open Studio version is not properly installed. Ironbug worked properly when I copied the files as you indicated from the older Open Studio version.

Many thanks for your prompt response.
