### ISSUE TITLE
pollination 'PO Rooms' component does not work with IB_ThermalZone

### ISSUE THREAD

**Issue by TfedUD** [MingboPeng/Ironbug#45]
Not an issue that effects me personally in any way: just something I found while checking out the new IB release with PO components; I thought may be 'not intended functionality' you may be keen on being aware of:

Have re-computed script
ghpy code:
```python
rooms_ = [room for room in _model.rooms]
```
![image](https://user-images.githubusercontent.com/63176386/170824989-384a142d-4f29-4ef1-9ac1-b5a046ebcb06.png)

**Comment by MingboPeng** [comment]
Hi @TfedUD, finally this issue is fixed:
![image](https://user-images.githubusercontent.com/9031066/178171156-7fd38a8d-a128-4843-84a5-202f512d2710.png)

https://github.com/MingboPeng/Ironbug/pull/52

**Comment by TfedUD** [comment]
Awesome! Thanks @MingboPeng!
