### ISSUE TITLE
The IB_Schedule component currently only supports input from Schedule Rules.

### ISSUE THREAD

**Issue by GudaoStudio** [MingboPeng/Ironbug#86]
Hey,@MingboPeng 
I think I have found an error. The IB_Schedule component currently only supports input from Schedule Rules. Any other numeric text input will result in the following error:
![image](https://github.com/MingboPeng/Ironbug/assets/51848364/f23432e3-e4bb-4b1b-9421-f0e2338e7671)

```
1. Solution exception:Failed to set Availability Schedule! Please double check input data type, or schedule type! 
In most cases, some components only accepts "Temperature" schedule type instead of default "Dimensionless". 
If this is the case, please use ScheduleTypeLimits to set "UnitType" to an appropriate value.
Detail error message:
Failed to setAvailabilitySchedule with OpenStudio.ScheduleRuleset to OpenStudio.ZoneHVACBaseboardConvectiveElectric!
```
The description of ValuesOrRules allows for input of either a single-digit or a 24-digit numeric text list:
```
One value for all day or 24 values for each hour, or use a list of scheduleRules from Ironbug_ScheduleRules. The last ScheduleRule will be set to the default (base) schedule.
```
I hope my assessment is not mistaken and that I can assist you in troubleshooting these issues.

best，
Zhengrong

**Comment by MingboPeng** [comment]
Hi @GudaoStudio thanks for reporting this issue with detailed information. 
It is indeed a bug inside the Ironbug and I am able to locate the source of the issue. I just pushed a fix and this should work in the new release.
![image](https://github.com/MingboPeng/Ironbug/assets/9031066/5756e79b-f45e-46e4-8c00-a5b949778f0e)
