### ISSUE TITLE
Issue with Defining Values for Curve Exponent x

### ISSUE THREAD

**Issue by GudaoStudio** [MingboPeng/Ironbug#89]
Hey,@MingboPeng 
When I tried to define values for Maximum Value Of X and Minimum Value Of X, it showed the following error:
![image](https://github.com/MingboPeng/Ironbug/assets/51848364/8a92f8a9-fefe-4d54-b7aa-7aa575cbddc0)

```
1. Solution exception:Failed to set Maximum Valueofx! Please double check input data type, or typo! 
Detail error message:
对象与目标类型不匹配。
```
I canceled the inputs for Maximum Value Of X and Minimum Value Of X and kept the defaults, and the component output was fine.

![image](https://github.com/MingboPeng/Ironbug/assets/51848364/a8a56e56-02ac-4db3-8ffa-017e7e528246)

This is a minor issue, but it can easily perplex explorers (like myself). ：)

best.
Zhengrong

**Comment by MingboPeng** [comment]
Hi @GudaoStudio thanks for the issue. It is indeed a bug in the CurveExponent component. Here is fixed.
![image](https://github.com/MingboPeng/Ironbug/assets/9031066/80c1c38c-698b-408e-b3f5-7131f3ae1de4)
